# Generated by CMake 2.8.10.2

IF("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   MESSAGE(FATAL_ERROR "CMake >= 2.6.0 required")
ENDIF("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
CMAKE_POLICY(PUSH)
CMAKE_POLICY(VERSION 2.6)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
SET(CMAKE_IMPORT_FILE_VERSION 1)

# Create imported target cudpp
ADD_LIBRARY(cudpp STATIC IMPORTED)

# Create imported target cudpp_hash
ADD_LIBRARY(cudpp_hash STATIC IMPORTED)

# Make sure the targets which have been exported in some other 
# export set exist.

# Import target "cudpp" for configuration ""
SET_PROPERTY(TARGET cudpp APPEND PROPERTY IMPORTED_CONFIGURATIONS NOCONFIG)
SET_TARGET_PROPERTIES(cudpp PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_NOCONFIG "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_NOCONFIG "/usr/local/cuda/lib64/libcudart.so;/usr/lib64/libcuda.so"
  IMPORTED_LOCATION_NOCONFIG "/home/yabuta/joins/hashJoin_gpu/other/cudpp_test/lib/libcudpp.a"
  )

# Make sure the targets which have been exported in some other 
# export set exist.

# Import target "cudpp_hash" for configuration ""
SET_PROPERTY(TARGET cudpp_hash APPEND PROPERTY IMPORTED_CONFIGURATIONS NOCONFIG)
SET_TARGET_PROPERTIES(cudpp_hash PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_NOCONFIG "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_NOCONFIG "/usr/local/cuda/lib64/libcudart.so;/usr/lib64/libcuda.so;cudpp"
  IMPORTED_LOCATION_NOCONFIG "/home/yabuta/joins/hashJoin_gpu/other/cudpp_test/lib/libcudpp_hash.a"
  )

# Commands beyond this point should not need to know the version.
SET(CMAKE_IMPORT_FILE_VERSION)
CMAKE_POLICY(POP)
